name: kfcChat
namespace: bf-kfc
defaultLanguage: en
nluThreshold: 0.75
timezoneOffset: 0
allowContextualQuestions: false
instance:
  name: Default Instance
  host: 'http://localhost:5005'
  projectId: hxiuJthS2tWvfdjFW
